{% set name = "himalaya" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/soywod/himalaya/archive/v{{ version }}.tar.gz
  sha256: 9a5593a3a92dcce8227cea45870a88432d8df3a012636eb5461165cf599dbcbb

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

test:
  commands:
    - himalaya --help

about:
  home: https://github.com/soywod/himalaya
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CLI email client written in Rust
  dev_url: https://github.com/soywod/himalaya

extra:
  recipe-maintainers:
    - danielnachun
