context:
  version: "2.2.1"

package:
  name: himalaya
  version: ${{ version }}

source:
  url: https://github.com/soywod/himalaya/archive/v${{ version }}.tar.gz
  sha256: 261b6d3bce4f0de6399b347525fc3c687f309d83840b4e10a58ab7ad70c03544

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - libgit2
  host:
    - openssl

tests:
  - script:
      - himalaya --help

about:
  license: MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: CLI email client written in Rust
  homepage: https://github.com/soywod/himalaya
  repository: https://github.com/soywod/himalaya

extra:
  recipe-maintainers:
    - danielnachun
