context:
  version: 0.9.0

package:
  name: himalaya
  version: ${{ version }}

source:
  url: https://github.com/soywod/himalaya/archive/v${{ version }}.tar.gz
  sha256: 9a5593a3a92dcce8227cea45870a88432d8df3a012636eb5461165cf599dbcbb

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - himalaya --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CLI email client written in Rust
  homepage: https://github.com/soywod/himalaya
  repository: https://github.com/soywod/himalaya

extra:
  recipe-maintainers:
    - danielnachun
