context:
  version: "1.1.0"

package:
  name: himalaya
  version: ${{ version }}

source:
  url: https://github.com/soywod/himalaya/archive/v${{ version }}.tar.gz
  sha256: bc5ee10ebdb23ea205215650070373dc591f083a96b1d6d038aa23a105256f94

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - himalaya --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CLI email client written in Rust
  homepage: https://github.com/soywod/himalaya
  repository: https://github.com/soywod/himalaya

extra:
  recipe-maintainers:
    - danielnachun
